apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  db-name: {{ .Values.db.name }}
  db-user: {{ .Values.db.user }}
  db-password: {{ .Values.db.password }}
