[servers]
srv ansible_host=84.201.175.91 ansible_user=ubuntu

[k8s_master]
k8s-master ansible_host=10.0.1.10 ansible_user=ubuntu ansible_ssh_common_args='-o ProxyJump=ubuntu@84.201.175.91'

[k8s_nodes]
k8s-app ansible_host=10.0.1.11 ansible_user=ubuntu ansible_ssh_common_args='-o ProxyJump=ubuntu@84.201.175.91'

[k8s:children]
k8s_master
k8s_nodes
